services:
  db:
    image: mysql:9.1.0
    ports:
      - ${MYSQL_PORT:-3306}:3306
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=cws
      - MYSQL_PASSWORD=cws_password
      - MYSQL_ROOT_PASSWORD=cws_root_password
  php:
    image: asifcws/php:v8.4.0
    command: bash -c "composer install --no-dev && sh docker-start.sh"
    ports:
      - 9000:9000
    volumes:
      - .:/usr/share/nginx/html   
    working_dir: /usr/share/nginx/html
    environment:
      APP_KEY: base64:LNlusOEjWdr1Ym7Pc0jDl4C4aqK6pBWc+UIhBsovRYo=
      DB_CONNECTION: mysql
      DB_DATABASE: laravel
      DB_USERNAME: cws
      DB_PASSWORD: cws_password
      DB_HOST: db
    depends_on:
      - db
    restart: on-failure  
  webserver: 
    image: asifcws/nginx:v1.0.0
    ports:
      - ${HTTP_PORT:-80}:80
    volumes:
      - .:/usr/share/nginx/html  
    depends_on: 
      - db
      - php
    restart: on-failure